import type { KeywordCard } from './types';

export const KEYWORD_DECK: KeywordCard[] = [
  { id: 'c1', words: ['House', 'Firefighter', 'Pond', 'Lamp'] },
  { id: 'c2', words: ['Hood', 'Sheep', 'Climbing', 'Pear'] },
  { id: 'c3', words: ['Doe', 'Clothing', 'Banana', 'Tattoo'] },
  { id: 'c4', words: ['Shirt', 'Tail', 'Menu', 'Child'] },
  { id: 'c5', words: ['Memory', 'Down', 'Guide', 'Love'] },
  { id: 'c6', words: ['Castle', 'Knight', 'Crown', 'Sword'] },
  { id: 'c7', words: ['River', 'Boat', 'Bridge', 'Fish'] },
  { id: 'c8', words: ['Apple', 'Tree', 'Forest', 'Leaves'] },
  { id: 'c9', words: ['Sun', 'Beach', 'Summer', 'Sand'] },
  { id: 'c10', words: ['Moon', 'Night', 'Star', 'Dream'] },
  { id: 'c11', words: ['Coffee', 'Morning', 'Mug', 'Wake'] },
  { id: 'c12', words: ['Book', 'School', 'Teacher', 'Paper'] },
  { id: 'c13', words: ['Guitar', 'Music', 'Song', 'Dance'] },
  { id: 'c14', words: ['Doctor', 'Hospital', 'Medicine', 'Heart'] },
  { id: 'c15', words: ['Rocket', 'Space', 'Planet', 'Alien'] },
  { id: 'c16', words: ['Train', 'Track', 'Ticket', 'Station'] },
  { id: 'c17', words: ['Pizza', 'Cheese', 'Oven', 'Tomato'] },
  { id: 'c18', words: ['Clock', 'Hour', 'Watch', 'Minute'] },
  { id: 'c19', words: ['Winter', 'Snow', 'Ice', 'Cold'] },
  { id: 'c20', words: ['Mountain', 'Peak', 'Hike', 'Rock'] },
  { id: 'c21', words: ['Ocean', 'Wave', 'Sailor', 'Whale'] },
  { id: 'c22', words: ['Dog', 'Bark', 'Leash', 'Bone'] },
  { id: 'c23', words: ['Cat', 'Whisker', 'Paws', 'Milk'] },
  { id: 'c24', words: ['Car', 'Wheel', 'Road', 'Engine'] },
  { id: 'c25', words: ['Gold', 'Treasure', 'Chest', 'Coin'] },
  { id: 'c26', words: ['King', 'Queen', 'Prince', 'Throne'] },
  { id: 'c27', words: ['Bird', 'Wing', 'Feather', 'Sky'] },
  { id: 'c28', words: ['Camp', 'Fire', 'Tent', 'Woods'] },
  { id: 'c29', words: ['Magic', 'Wand', 'Spell', 'Wizard'] },
  { id: 'c30', words: ['Garden', 'Flower', 'Rose', 'Soil'] },
  { id: 'c31', words: ['Bread', 'Butter', 'Bakery', 'Toast'] },
  { id: 'c32', words: ['Cinema', 'Movie', 'Screen', 'Popcorn'] },
  { id: 'c33', words: ['Painting', 'Brush', 'Color', 'Art'] },
  { id: 'c34', words: ['Camera', 'Photo', 'Lens', 'Smile'] },
  { id: 'c35', words: ['Police', 'Badge', 'Siren', 'Law'] },
  { id: 'c36', words: ['Farm', 'Cow', 'Barn', 'Tractor'] },
  { id: 'c37', words: ['Ring', 'Diamond', 'Jewel', 'Wedding'] },
  { id: 'c38', words: ['Key', 'Lock', 'Door', 'Secret'] },
  { id: 'c39', words: ['Hammer', 'Nail', 'Wood', 'Tool'] },
  { id: 'c40', words: ['Mirror', 'Glass', 'Reflect', 'Shadow'] }
];
